import type { Metadata } from "next";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          type="text/css"
          rel="stylesheet"
          href="/assets/style/bulma.min.css"
        />
      </head>
      <body>
        <Navbar />
        <section className="hero is-link is-fullheight-with-navbar">
          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
